### ISSUE TITLE
Use pull requests to automate changelogs for releases

### ISSUE THREAD

**Issue by ohaeusler** [Gruppe-Ausschussexterner-Programmierer/color-poll#6]

**Comment by ohaeusler** [comment]
Even if you're the owner of a repository ^^

**Comment by heofthetea** [comment]
i dunno technically only one of us is actually working on this currently, furthermore we're basically done - So no, I don't think I will ;)
![maxresdefault](https://user-images.githubusercontent.com/66491218/149422286-25f9ad2c-9e87-4eae-8502-853894494507.png)
